#!/bin/sh
. /etc/functions.sh

jffs2_ready () {
    echo -e "jffs2_ready() starts...\n"
        mtdpart="$(find_mtd_part rootfs_data)"
        magic=$(hexdump $mtdpart -n 4 -e '4/1 "%02x"')
        [ "$magic" != "deadc0de" ]
}

if grep rootfs_data /proc/mtd >/dev/null 2>/dev/null; then {
        echo "rootfs_data is available"
	. /bin/firstboot
        mtd unlock rootfs_data
	{
                echo "switching to jffs2"
                mount "$(find_mtd_part rootfs_data)" /jffs -t jffs2 && \
                        fopivot /jffs /rom
        } || {
                echo "jffs2 not ready yet; using ramdisk"
                ramoverlay
        }
}
elif grep mmcblk0p1 /proc/partitions > /dev/null 2>/dev/null; then {
	echo "sd/mmc card is available"
	. /bin/firstboot
	{
	    echo "switching to sd/mmc"
	    mount /dev/mmcblk0p1 /mmc -t ext2
	    if grep /dev/mmcblk0p1 /proc/mounts; then
		echo "sd/mmc card is mounted"
	    else
		echo "sd/mmc card is not mounted!"
	    fi
	    fopivot /mmc /rom
	} || {
	    echo "sd/mmc card not ready yet; using ramdisk"
	    ramoverlay
	}
}
else {
        echo "Both rootfs_data and sd/mmc are not available"
        mtd unlock rootfs
        mount -o remount,rw /dev/root /
}
fi
