#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
. /etc/diag.sh

# Mount
mount proc /proc -t proc
mount sysfs /sys -t sysfs
size=$(awk '/MemTotal:/ {l=5242880;mt=($2*1024);print((s=mt/2)<l)&&(mt>l)?mt-l:s}' /proc/meminfo)
mount tmpfs /tmp -t tmpfs -o size=$size,nosuid,nodev,mode=1777
mkdir -p /dev/pts /dev/shm
mount devpts /dev/pts -t devpts

# Use /dev/pty/m0, m1 to replace /dev/console in case no serial console available
dd if=/dev/console of=/dev/null bs=1 count=0 >/dev/null 2>/dev/null && {
	M0=/dev/console
	M1=/dev/console
}
exec <$M0 >$M1 2>&0

# Start preinit to setup Unionfs
echo "- vtss-preinit -"
trap 'FAILSAFE=true' INT
trap 'FAILSAFE=true' USR1
if [ -e /etc/preinit.arch ]; then
	. /etc/preinit.arch
else
	sleep 2
fi

set_state preinit
export FAILSAFE
eval ${FAILSAFE:+failsafe}
lock -w /tmp/.failsafe

if [ -z "$INITRAMFS" ]; then
	mount_root
	echo "- vtss-init -"
	exec /sbin/init
fi
